// import localFont from "next/font/local";
// import "./globals.css";

// import Navbar from "@/components/user/NavBar";
import Navbar from "@/components/user/navbar";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "SkillEdge AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-white dark:bg-gray-900 text-black dark:text-white`}  
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
